name: sample
description: A sample that showcases simprokmachine features.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.27.3
  provider: ^6.0.2
  simprokmachine: ^1.1.1
  shared_preferences: ^2.0.13
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
